/**
 * Vegetable store
 * A simple vegatable store
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hitheshvdevadiga@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.Vegetables
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object VegetablesApi {

  /**
   * 
   * 
   * Expected answers:
   *   code 200 : Vegetables (OK)
   *   code 400 :  (error)
   * 
   * @param body 
   */
  def 2(body: Option[Vegetables] = None): ApiRequest[Vegetables] =
    ApiRequest[Vegetables](ApiMethods.POST, "http://localhost:9473", "/vegetable", "application/json")
      .withBody(body)
      .withSuccessResponse[Vegetables](200)
      .withErrorResponse[Unit](400)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (successfully updated)
   *   code 400 :  (error)
   * 
   * @param body 
   */
  def 3(body: Option[Vegetables] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.PUT, "http://localhost:9473", "/vegetable", "application/json")
      .withBody(body)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : Vegetables (OK)
   *   code 400 :  (error)
   */
  def vegetableGet(): ApiRequest[Vegetables] =
    ApiRequest[Vegetables](ApiMethods.GET, "http://localhost:9473", "/vegetable", "application/json")
      .withSuccessResponse[Vegetables](200)
      .withErrorResponse[Unit](400)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (deleted successfully)
   *   code 400 :  (error)
   * 
   * @param id 
   */
  def vegetableIdDelete(id: Int): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, "http://localhost:9473", "/vegetable/{id}", "application/json")
      .withPathParam("id", id)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : Vegetables (OK)
   *   code 400 :  (error)
   * 
   * @param id 
   */
  def vegetableIdGet(id: Int): ApiRequest[Vegetables] =
    ApiRequest[Vegetables](ApiMethods.GET, "http://localhost:9473", "/vegetable/{id}", "application/json")
      .withPathParam("id", id)
      .withSuccessResponse[Vegetables](200)
      .withErrorResponse[Unit](400)
      

}

