/**
 * Vegetable store
 * A simple vegatable store
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hitheshvdevadiga@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Vegetables (
  id: Option[Int] = None,
  name: Option[String] = None,
  quantity: Option[Int] = None,
  price: Option[Double] = None,
  status: Option[VegetablesEnums.Status] = None
) extends ApiModel

object VegetablesEnums {

  type Status = Status.Value
  object Status extends Enumeration {
    val Available = Value("available")
    val OutOfStock = Value("out of stock")
  }

}

